# Constants
module Constants
  # ConstantsBillingTerm
  module ConstantsAgency
    ALL_STATUS = [ 'Enabled', 'Disabled', 'Pending'].freeze

    BLOCKED_DOMAINS = %w(
      gmail
      30gigs
      aol
      aussiemail
      bigstring
      bluebottle
      boarderemail
      canada
      canoe
      care2
      dcemail
      dbzmail
      didamail
      emailaccount
      fastermail
      fastmail
      gawab
      graffiti
      hotpop
      hushmail
      icqmail
      inbox
      indiatimes
      inmail24
      jubii
      linuxmail
      litepost
      lycos
      mail
      mail2world
      mailsnare
      merseymail
      hotmail
      muchomail
      myway
      operamail
      outgun
      postmaster
      prontomail
      rediff
      rediffmail
      runbox
      sacmail
      safe-mail
      ureach
      vfemail
      yahoo
      zilladog
      email
      tools
      myemail
      fuser
      grabmail
      jump2email
      mail2web
      myemail
      tamadaa
      techemail
      earthclassmail
      futureme
      hoaxmail
      l8r
      postful
      pranketh
      shinyletter
      2prong
      dodgeit
      e4ward
      emailias
      gishpuppy
      guerrillamail
      mailexpire
      mailnator
      pookmail
      spam
      spambox
      spamex
      spamgourmet
      tempinbox
      zoemail
    ).freeze

  end
end
